version: '3'

services:
  pear:
    image: sushi-backend
    build: .
    container_name: sushi-backend-server
    ports:
      - "5555:8081"
    networks:
      - redis-network
  redis:
    image: redis
    container_name: redis-sushi
    ports:
      - "6391:6379"
    networks:
      - redis-network
networks:
  redis-network: