# json name을 snake case로 변환해서 정보를 주고 받음
server:
  jackson:
    property-naming-strategy: SNAKE_CASE

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY:sushides}
    exp:
      access: ${JWT_ACCESS_EXP:3600}
      refresh: ${JWT_REFRESH_EXP:15000}
    header:
      access: ${JWT_HEADER:Authorization}
      refresh: ${JWT_REFRESH_HEADER:X-Refresh-Token}
    prefix: ${JWT_PREFIX:Bearer}