# json name을 snake case로 변환해서 정보를 주고 받음
server:
  jackson:
    property-naming-strategy: SNAKE_CASE

spring:
  datasource:
    url: ${DB_URL} # jdbc:mysql://{host}:{port}/{db_name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

auth:
  jwt:
    secret: ${JWT_SECRET_KEY}
    exp:
      access: ${JWT_ACCESS_EXP:4000}
    header:
      access: ${JWT_HEADER:Authorization}
    prefix: ${JWT_PREFIX:Bearer}

file:
  path: ${FILE_PATH}
